name: taks_daily_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0<4.0.0'

dependencies:
  auto_route: ^9.2.2
  awesome_dio_interceptor: ^1.2.0
  camera: ^0.11.0+2
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  dio: ^5.6.0
  envied: ^0.5.4+1
  expansion_widget: ^0.1.0
  firebase_auth: any
  firebase_core: any
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_facebook_auth: any
  flutter_native_splash: ^2.4.1
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.8
  fpdart: ^1.1.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  injectable: ^2.4.4
  intl: ^0.19.0
  json_annotation: ^4.9.0
  path_provider: ^2.1.4
  provider: ^6.0.5
  sqflite: ^2.3.3+1
  shared_preferences: any 

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.12
  flutter_flavorizr: ^2.2.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  very_good_analysis: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/img/
    - assets/svg/
